const EnrolData: Array<IEnrolData> = [
  {
    id: 1,
    title: "Cambridge Practicals",
    description: "Mondays",
    secondary: "4:00pm - 6:30pm (IST)",
    tertiary: "10:30am - 01:00pm (GMT)",
    button: "Enrol Now",
    image: "/img/EnrolIcons/cam-prac.png",
    extras: "mx-20",
  },
  {
    id: 2,
    title: "Cambridge ALs 2023",
    description: "Wednesday",
    secondary: "4:00pm - 6:30pm",
    tertiary: "10:30am - 01:00pm (GMT)",
    button: "Enrol Now",
    image: "/img/EnrolIcons/cam-al-1.png",
    extras: "mx-20",
  },
  {
    id: 3,
    title: "Cambridge ALs 2024",
    description: "Thursday",
    secondary: "4:00pm - 6:30pm (IST)",
    tertiary: "10:30am - 01:00pm (GMT)",
    button: "Enrol Now",
    image: "/img/EnrolIcons/cam-al-1.png",
    extras: "mx-20",
  },
  {
    id: 4,
    title: "Edexcel ALs 2024",
    description: "Saturday",
    secondary: "10:30am - 1:00pm (IST)",
    tertiary: "05:00am - 07:30pm (GMT)",
    button: "Enrol Now",
    image: "/img/EnrolIcons/edx-al-1.png",
    extras: "mx-20",
  },
  {
    id: 5,
    title: "Edexcel ALs 2023",
    description: "Sunday",
    secondary: "10:30am - 1:00pm (IST)",
    tertiary: "05:00am - 07:30pm (GMT)",
    button: "Enrol Now",
    image: "/img/EnrolIcons/edx-al-2.png",
    extras: "mx-20",
  },
  {
    id: 6,
    title: "Edexcel IGCSEs 2024",
    description: "Saturday",
    secondary: "3:30pm - 5:30pm (IST)",
    tertiary: "10:00am - 12:00pm (GMT)",
    button: "Enrol Now",
    image: "/img/EnrolIcons/edx-ol-1.png",
    extras: "mx-20",
  },
];

export default EnrolData;
